/** Production WebP base path for Brave Heart marketing assets. */
export const BRAVEHEART_IMAGE_BASE = '/assets/images/braveheart/';

/** Width variants generated by scripts/generate-responsive-images.mjs */
export const INFOGRAPHIC_SRCSET_WIDTHS = [640, 960, 1280] as const;
export const PORTRAIT_SRCSET_WIDTHS = [256, 384, 512] as const;

export function braveheartImageSrc(filename: string): string {
  return `${BRAVEHEART_IMAGE_BASE}${filename}`;
}

function stripWebpExt(filename: string): string {
  return filename.replace(/\.webp$/i, '');
}

function variantFilename(filename: string, width: number): string {
  return `${stripWebpExt(filename)}-${width}w.webp`;
}

export function braveheartVariantSrc(filename: string, width: number): string {
  return braveheartImageSrc(variantFilename(filename, width));
}

export function buildSrcSet(filename: string, widths: readonly number[]): string {
  return widths
    .map((w) => `${braveheartVariantSrc(filename, w)} ${w}w`)
    .join(', ');
}

/** Full-bleed infographics inside ~max-w-4xl content columns. */
export const INFOGRAPHIC_SIZES =
  '(max-width: 640px) 100vw, (max-width: 1024px) 90vw, 896px';

/** Edge-to-edge banner infographics (Heroes Journey on Home). */
export const FULL_BLEED_SIZES = '(max-width: 1920px) 100vw, 1920px';

/** Founder portrait — fixed display box up to ~224px. */
export const PORTRAIT_SIZES =
  '(max-width: 640px) 176px, (max-width: 768px) 192px, 224px';

export function infographicSrcSet(filename: string): string {
  return buildSrcSet(filename, INFOGRAPHIC_SRCSET_WIDTHS);
}

export function portraitSrcSet(filename: string): string {
  return buildSrcSet(filename, PORTRAIT_SRCSET_WIDTHS);
}

/** Smallest variant as a lightweight default `src` for infographics. */
export function infographicDefaultSrc(filename: string): string {
  return braveheartVariantSrc(filename, INFOGRAPHIC_SRCSET_WIDTHS[0]);
}

export function portraitDefaultSrc(filename: string): string {
  return braveheartVariantSrc(filename, PORTRAIT_SRCSET_WIDTHS[0]);
}

/** Standard Brave Heart infographic canvas (1376×768). */
export const STANDARD_INFOGRAPHIC_DIMENSIONS = { width: 1376, height: 768 } as const;

/** Per-file overrides when dimensions differ from the standard canvas. */
const INFOGRAPHIC_DIMENSION_OVERRIDES: Record<string, { width: number; height: number }> = {
  'braveheart-client-heroes-journey.webp': { width: 1382, height: 769 },
};

export function infographicDimensions(filename: string): { width: number; height: number } {
  return INFOGRAPHIC_DIMENSION_OVERRIDES[filename] ?? STANDARD_INFOGRAPHIC_DIMENSIONS;
}
